---
qintro: "It is important that these Icons don’t just invite us to reflect but
  that they move us into action. Below you will find some practices to be
  explored on your own or in groups and some questions that you and others may
  wish to reflect upon:"
