backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo:  Alasdair-Munday/icons-discipleship 
media_folder: "src/static/img"
public_folder: "/static/img"
publish_mode: editorial_workflow

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Icons"
    name: "icons"
    folder: "src/icons"
    create: false
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Bible Passages"
        name: "passages"
        widget: "list"
        summary: '{{fields.reference}}'
        fields:
          - {label: Reference, name: reference, widget: string}
          - {label: Text, name: text, widget: text}
      - label: "Practices"
        name: "practices"
        widget: "list"
        summary: '{{fields.practice}}'
        fields: 
          - {label: Practice,
            name: practice,
            widget: relation,
            collection: practices,
            search_fields: [title],
            display_fields: ["title"],
            value_field: "{{slug}}" }
          - {label: description, required: false, name: text, widget: string}
            
      - label: "Questions"
        name: "questions"
        widget: "list"
        summary: '{{fields.question}}'
        field: {label: Question, name: question, widget: string}

  - label: "Practices"
    name: "practices"
    folder: "src/practices"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Icon Settings"
        name: icon_settings
        file: src/_data/iconSettings.yaml
        fields:
          - { label: "Questions Introduction", name: "qintro", widget: "text" }
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: URL, name: url, widget: string }
