backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo:  Alasdair-Munday/icons-discipleship 
media_folder: "src/static/img"
public_folder: "/static/img"
publish_mode: editorial_workflow

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Icons"
    name: "icons"
    folder: "src/icons"
    create: false
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Bible Passages"
        name: "passages"
        widget: "list"
        summary: '{{fields.reference}}'
        fields:
          - {label: Reference, name: reference, widget: string}
          - {label: Text, name: text, widget: text}
      - label: "Questions"
        name: "questions"
        widget: "list"
        summary: '{{fields.question}}'
        fields:
          - {label: Question, name: question, widget: string}
          - {label: Practice,
            required: false,
            name: practice,
            widget: relation,
            collection: practices,
            search_fields: [title],
            display_fields: ["title"],
            value_field: "{{slug}}" }

  - label: "Practices"
    name: "practices"
    folder: "src/practices"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - label: "Worksheets"
    name: "worksheets"
    folder: "src/worksheets"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }
      - label: "Icons"
        name: "icons"
        widget: "object"
        fields: 
          - { label: "Cross", name: "cross", widget: markdown }
          - { label: "Fire", name: "fire", widget: markdown }
          - { label: "Seeds", name: "seeds", widget: markdown }
          - { label: "Table", name: "table", widget: markdown }
          - { label: "Vine", name: "vine", widget: markdown }
      - { label: "Summary", name: "summary", required: false, widget: "markdown" }

  - label: "Main pages"
    name: "mainpages"
    editor:
      preview: false
    files:
      - label: "Worksheets"
        name: "worksheets"
        file: src/worksheets.md
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Homepage"
        name: "homepage"
        file: src/home.md
        fields:
          - { label: "Before Icons", name: "body", widget: "markdown" }
          - { label: "After Icons", name: "after", widget: "markdown" }
      - label: "Practices"
        name: "practices"
        file: src/practices.md
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Icons"
        name: "icons_index"
        file: src/icons.md
        fields:
          - { label: "Before Icons", name: "body", widget: "markdown" }
          - { label: "After Icons", name: "after", widget: "markdown" }
      - label: "Discipleship"
        name: "discipleship"
        file: src/discipleship.md
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Rule Of Life"
        name: "rule_of_life"
        file: src/rule_of_life.md
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Icon Settings"
        name: icon_settings
        file: src/_data/iconSettings.yaml
        fields:
          - { label: "Questions Introduction", name: "qintro", widget: "text" }
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: URL, name: url, widget: string }
